### ISSUE TITLE
请问获取用户离线消息数可以加入下么..现在环信更新了好多api了..

### ISSUE THREAD

**Issue by uniteweiwei** [link1st/laravel-easemob#7]
` 
   /**
     * 获取用户离线消息数
     *
     * @param $user_name
     *
     * @return mixed
     */
    public function offlineMsgCount($user_name)
    {
        $url          = $this->url.'users/'.$user_name.'/offline_msg_count';
        $option       = [];
        $access_token = $this->getToken();
        $header []    = 'Authorization: Bearer '.$access_token;

        return Http::postCurl($url, $option, $header, 'GET');
    }
`

**Comment by uniteweiwei** [comment]
quhang/laravel-easemob  这个包比较全,就是不支持不更新了..不支持laravel6

**Comment by uniteweiwei** [comment]
![image](https://user-images.githubusercontent.com/19373139/84463755-41b23200-aca5-11ea-879c-72f88bf841da.png)
另外,修改密码有个bug

**Comment by link1st** [comment]
获取用户离线消息数 已经添加，下次可以用 `git merge` 的方式，然后我来合并

第二个问题，很久以前就修复了，估计你下载的不是最新的代码 我重新添加了一个 tag **v0.1.1** 可以使用这个版本的代码

**Comment by uniteweiwei** [comment]
你好,我不太会用这个git merge的方式哦,请问是在
![image](https://user-images.githubusercontent.com/19373139/84472850-94e2af80-acba-11ea-8a9d-f9674f4c58a5.png)
这里拉下来,更改么

**Comment by link1st** [comment]
是这个
步骤:
1、先 fork 这个项目
2、把自己 fork 的项目 clone 本地
3、新的修改提交到 github
4、然后在自己 fork 的项目上 点击 `New pull request`
